version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: smartlink_db
    environment:
      MYSQL_DATABASE: 'smartlink' 
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - smartlink-db:/var/lib/mysql
    networks:
      - backend
    depends_on:
      - app
  
  app:
    container_name: smartlink_app
    build: .
    ports:
      - 8000:8000
    restart: on-failure
    networks:
      - backend
 
volumes:
  smartlink-db:
networks:
  backend:
    driver: bridge